In [13]:
import numpy as np

# Create an array
a = np.array([[1, 2], [3, 4]])
print("Array:\n", a)

# Dot product
b = np.array([[5, 6], [7, 8]])
dot = np.dot(a, b)
print("Dot Product:\n", dot)

Array:
 [[1 2]
 [3 4]]
Dot Product:
 [[19 22]
 [43 50]]


In [15]:
np3 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
#print(np3[2:6])
np4 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(np4[1][2])
# slicing a 2d array
print(np4[0:1, 1:3])
print(np4[0:, 1:3])

8
[[2 3]]
[[2 3]
 [7 8]]


In [17]:
#some universal functions in numpy
np1 = np.array([-5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(np1)

#print(np.sqrt(np1))

#print(np.absolute(np1))

#print(np.exp(np1))

#print(np.max(np1))
#print(np.min(np1))

#print(np.sign(np1))

#Trigonometry
print(np.sin(np1))
print(np.log(np1[6:]))
print(np.cos(np1))


[-5 -4 -3 -2 -1  0  1  2  3  4  5  6  7  8  9]
[ 0.95892427  0.7568025  -0.14112001 -0.90929743 -0.84147098  0.
  0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866   0.98935825  0.41211849]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]
[ 0.28366219 -0.65364362 -0.9899925  -0.41614684  0.54030231  1.
  0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219  0.96017029
  0.75390225 -0.14550003 -0.91113026]


In [19]:
np1 = np.array([1, 2, 3, 4, 5])
# Creating a view

np2 = np1.view()
print(f"Original np1: {np1}")
print(f"Original np2: {np2}")

np1[0] = 7

print(f"Changed np1: {np1}")
print(f"Original np2: {np2}")

"""
Creating a copy
np2 =  np1.copy()
print(f"Original np1: {np1}")
print(f"Original np2: {np2}")

np1[0] = 7

print(f"Changed np1: {np1}")
print(f"Original np2: {np2}")
"""

Original np1: [1 2 3 4 5]
Original np2: [1 2 3 4 5]
Changed np1: [7 2 3 4 5]
Original np2: [7 2 3 4 5]


'\nCreating a copy\nnp2 =  np1.copy()\nprint(f"Original np1: {np1}")\nprint(f"Original np2: {np2}")\n\nnp1[0] = 7\n\nprint(f"Changed np1: {np1}")\nprint(f"Original np2: {np2}")\n'

In [21]:
# Shape and Reshape numpy arrays

# Create a 1-D array and find its shape
np1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print(np1)
print(np1.shape)

# Create a 2-D array and get shape(rows/columns)
#np2 = np.array([[1, 2, 3, 4, 5, 6], [7, 8, 9, 10, 11, 12]])
#print(np2)
#print(np2.shape)

# Reshape 2-D
np3 = np1.reshape(3, 4)
print(np3)

# Reshape 3-D
np4 = np1.reshape(2, 3, 2)
print(np4)

# Flatten to 1-D
np5 = np4.reshape(-1)
print(np5)
print(np5.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)


In [43]:
# iterating through numpy array

#1-D
#np1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
#for i in np1:
 #   print(i)

#2-D
#np2 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
#for i in np2:
 #   print(i)
  #  for j in i:
   #     print(j)

#3-D
np3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
"""
for i in np3:
    #print(i)
    for j in i:
        #print(j)
        for k in j:
            print(k)
"""
for i in np.nditer(np3):
    print(i)
    


1
2
3
4
5
6
7
8
9
10
11
12


In [51]:
# sorting
np1 = np.array([6, 7, 4, 9, 0, 2, 1])
print(np.sort(np1))

np2 = np.array(['John', 'Krish', 'Qazi', 'Jim'])
print(np.sort(np2))


#2-D
np3 = np.array([[6, 2, 8, 10, 5], [3, 1, 7, 4, 9]])
print(np.sort(np3))
print(np.sort(np.nditer(np3)))

[0 1 2 4 6 7 9]
['Jim' 'John' 'Krish' 'Qazi']
[[ 2  5  6  8 10]
 [ 1  3  4  7  9]]
[ 1  2  3  4  5  6  7  8  9 10]


In [71]:
#Searcching
np1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 3, 10])
x = np.where(np1 == 3)
print(x)
print(x[0])

# even items
y = np.where(np1 % 2 == 0)
print(y[0])

(array([2, 9], dtype=int64),)
[2 9]
[ 1  3  5  7 10]


In [81]:
# Filtering
np1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
#x = [True, True, False, False, False, False, False, False, False, False]
#print(np1)
#print(np1[x])

"""
filtered = []
for item in np1:
    if (item % 2 == 0):
        filtered.append(True)
    else:
        filtered.append(False)

print(np1[filtered])
"""
filtered = np1 % 2 == 0
print(filtered)
print(np1[filtered])

[False  True False  True False  True False  True False  True]
[ 2  4  6  8 10]
